### ISSUE TITLE
triplet loss

### ISSUE THREAD

**Issue by kunkun0w0** [Snailpong/reference_based_sketch_image_colorization#1]
hi~ I have some questions about triplet loss.
In section 3.4, Lee seems to use the ground truth correspondence to supervise the train of scft.
In my opinion, **we can input the ground truth image into the encoder and scft to get the positive keys.**

By the way, I'm confused about the FID result of this paper.
(It is about 10% difference from the results I reproduced) orz

**Comment by tjdtnsu** [comment]
I'm not sure if we need to input the ground truth image into the encoder and scft modele to generate the key.
(Many implementation on Github did not consider this maybe.)
What dataset did you used for FID calculation? Dataset of the paper would be mismatch with the data we collected.
I think you can check the score more accurately when you trained with ImageNet or CelebA .

Thank you for your issue!
